export const NYP_IMG = [
  {
    src: "/assets/imgs/nyp-bnr-1.webp",
    alt: "nyp-bnr-1.webp",
    width: 240,
    height: 204,
  },
  {
    src: "/assets/imgs/nyp-bnr-2.webp",
    alt: "nyp-bnr-2.webp",
    width: 240,
    height: 204,
  },
  {
    src: "/assets/imgs/nyp-bnr-3.webp",
    alt: "nyp-bnr-3.webp",
    width: 240,
    height: 204,
  },
  {
    src: "/assets/imgs/nyp-bnr-4.webp",
    alt: "nyp-bnr-4.webp",
    width: 240,
    height: 204,
  },
];

export const NYP_SP_IMG = [
  {
    src: "/assets/imgs/nyp-bnr-sp-1.webp",
    alt: "nyp-bnr-1.webp",
    width: 148,
    height: 128,
  },
  {
    src: "/assets/imgs/nyp-bnr-sp-2.webp",
    alt: "nyp-bnr-2.webp",
    width: 148,
    height: 128,
  },
  {
    src: "/assets/imgs/nyp-bnr-sp-3.webp",
    alt: "nyp-bnr-3.webp",
    width: 148,
    height: 128,
  },
  {
    src: "/assets/imgs/nyp-bnr-sp-4.webp",
    alt: "nyp-bnr-4.webp",
    width: 148,
    height: 128,
  },
];

export const MEM_BNR_IMG = [
  {
    src: "/assets/imgs/cats/cat (1).png",
    alt: "cat (1).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (2).png",
    alt: "cat (2).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (3).png",
    alt: "cat (3).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (4).png",
    alt: "cat (4).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (5).png",
    alt: "cat (5).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (6).png",
    alt: "cat (6).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (7).png",
    alt: "cat (7).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (8).png",
    alt: "cat (8).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (9).png",
    alt: "cat (9).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (10).png",
    alt: "cat (10).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (11).png",
    alt: "cat (11).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (12).png",
    alt: "cat (12).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (13).png",
    alt: "cat (13).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (14).png",
    alt: "cat (14).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (15).png",
    alt: "cat (15).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (16).png",
    alt: "cat (16).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (17).png",
    alt: "cat (17).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (18).png",
    alt: "cat (18).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (19).png",
    alt: "cat (19).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (20).png",
    alt: "cat (20).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (21).png",
    alt: "cat (21).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (22).png",
    alt: "cat (22).png",
    width: 48,
    height: 48,
  },
  {
    src: "/assets/imgs/cats/cat (23).png",
    alt: "cat (23).png",
    width: 48,
    height: 48,
  },
];

export const MEM_BNR_SP_IMG = [
  {
    src: "/assets/imgs/cats/cat-sp (1).png",
    alt: "cat-sp (1).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (2).png",
    alt: "cat-sp (2).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (3).png",
    alt: "cat-sp (3).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (4).png",
    alt: "cat-sp (4).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (5).png",
    alt: "cat-sp (5).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (6).png",
    alt: "cat-sp (6).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (7).png",
    alt: "cat-sp (7).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (8).png",
    alt: "cat-sp (8).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (9).png",
    alt: "cat-sp (9).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (10).png",
    alt: "cat-sp (10).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (11).png",
    alt: "cat-sp (11).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (12).png",
    alt: "cat-sp (12).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (13).png",
    alt: "cat-sp (13).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (14).png",
    alt: "cat-sp (14).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (15).png",
    alt: "cat-sp (15).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (16).png",
    alt: "cat-sp (16).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (17).png",
    alt: "cat-sp (17).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (18).png",
    alt: "cat-sp (18).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (19).png",
    alt: "cat-sp (19).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (20).png",
    alt: "cat-sp (20).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (21).png",
    alt: "cat-sp (21).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (22).png",
    alt: "cat-sp (22).png",
    width: 32,
    height: 32,
  },
  {
    src: "/assets/imgs/cats/cat-sp (23).png",
    alt: "cat-sp (23).png",
    width: 32,
    height: 32,
  },
];
