export const CAT_REACTION_IMG = [
  [`/assets/imgs/reaction/cat/01cat-food.png`, "01cat-food.png"],
  [`/assets/imgs/reaction/cat/02pet-food.png`, "02pet-food.png"],
  [`/assets/imgs/reaction/cat/03pet-bowl.png`, "03pet-bowl.png"],
  [`/assets/imgs/reaction/cat/04cat-mask.png`, "04cat-mask.png"],
  [`/assets/imgs/reaction/cat/05cat-toy.png`, "05cat-toy.png"],
  [`/assets/imgs/reaction/cat/06wool-ball.png`, "06wool-ball.png"],
  [`/assets/imgs/reaction/cat/07wool.png`, "07wool.png"],
  [`/assets/imgs/reaction/cat/08play.png`, "08play.png"],
  [`/assets/imgs/reaction/cat/09mouse-toy.png`, "09mouse-toy.png"],
  [`/assets/imgs/reaction/cat/10rat.png`, "10rat.png"],
  [`/assets/imgs/reaction/cat/11litter-box.png`, "11litter-box.png"],
  [`/assets/imgs/reaction/cat/12maneki-neko.png`, "12maneki-neko.png"],
  [`/assets/imgs/reaction/cat/13medicine.png`, "13medicine.png"],
  [`/assets/imgs/reaction/cat/14paw01.png`, "14paw01.png"],
  [`/assets/imgs/reaction/cat/15paw02.png`, "15paw02.png"],
  [`/assets/imgs/reaction/cat/16shampoo.png`, "16shampoo.png"],
];

export const FOOD_REACTION_IMG = [
  ["/assets/imgs/reaction/food&drink/01apple.png", "01apple.png"],
  ["/assets/imgs/reaction/food&drink/02avocado.png", "02avocado.png"],
  ["/assets/imgs/reaction/food&drink/03fruit.png", "03fruit.png"],
  ["/assets/imgs/reaction/food&drink/04lemon.png", "04lemon.png"],
  ["/assets/imgs/reaction/food&drink/05mango.png", "05mango.png"],
  ["/assets/imgs/reaction/food&drink/06cherries.png", "06cherries.png"],
  ["/assets/imgs/reaction/food&drink/07candy-cane.png", "07candy-cane.png"],
  ["/assets/imgs/reaction/food&drink/08candy01.png", "08candy01.png"],
  ["/assets/imgs/reaction/food&drink/09candy02.png", "09candy02.png"],
  ["/assets/imgs/reaction/food&drink/10drinks.png", "10drinks.png"],
  ["/assets/imgs/reaction/food&drink/11juices.png", "11juices.png"],
  ["/assets/imgs/reaction/food&drink/12fish (1).png", "12fish (1).png"],
  ["/assets/imgs/reaction/food&drink/13fish (2).png", "13fish (2).png"],
  ["/assets/imgs/reaction/food&drink/14fish.png", "14fish.png"],
  ["/assets/imgs/reaction/food&drink/15gummy-bear.png", "15gummy-bear.png"],
  ["/assets/imgs/reaction/food&drink/16mushroom.png", "16mushroom.png"],
];
