export const CAT_REACT_IMG = [
  ["/assets/imgs/reaction/cat/01cat-food.", "01cat-food.png"],
  ["/assets/imgs/reaction/cat/02pet-food.", "02pet-food.png"],
  ["/assets/imgs/reaction/cat/03pet-bowl.", "03pet-bowl.png"],
  ["/assets/imgs/reaction/cat/04cat-mask.", "04cat-mask.png"],
  ["/assets/imgs/reaction/cat/05cat-toy.", "05cat-toy.png"],
  ["/assets/imgs/reaction/cat/06wool-ball.", "06wool-ball.png"],
  ["/assets/imgs/reaction/cat/07wool.png", "07wool.png"],
  ["/assets/imgs/reaction/cat/08play.png", "08play.png"],
  ["/assets/imgs/reaction/cat/09mouse-toy.", "09mouse-toy.png"],
  ["/assets/imgs/reaction/cat/10rat.png", "10rat.png"],
  ["/assets/imgs/reaction/cat/11litter-box.", "11litter-box.png"],
  ["/assets/imgs/reaction/cat/12maneki-neko.", "12maneki-neko.png"],
  ["/assets/imgs/reaction/cat/13medicine.png", "13medicine.png"],
  ["/assets/imgs/reaction/cat/14paw01.png", "14paw01.png"],
  ["/assets/imgs/reaction/cat/15paw02.png", "15paw02.png"],
  ["/assets/imgs/reaction/cat/shampoo.png", "shampoo.png"],
];
